# Generated by Django 2.2.3 on 2019-08-20 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20190820_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='item.Category'),
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
    ]
