# Generated by Django 2.2.3 on 2019-08-20 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='item.Tag'),
        ),
    ]
