"""
Django settings for point_mall project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*xnk*py=5u+v!96o*!s$ztbk5+i+y2+^q1qb)hh9xk3pm#_lh-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'user.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'oauth2_provider',
    'corsheaders',
    'rest_framework',
    'user.apps.UserConfig',
    'item.apps.ItemConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'point_mall.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'point_mall.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'point_mall',
        'USER': 'root',
        'PASSWORD': '1q2w3e4r',
        'HOST': 'point-mall.cyrkiqmrpyw9.us-east-1.rds.amazonaws.com',
        'PORT': '3306'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/


CORS_ORIGIN_ALLOW_ALL = True

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticated',),
#     'DEFAULT_AUTHENTICATION_CLASSES': ('rest_framework_simplejwt.authentication.JWTAuthentication',),
#
# }

OAUTH2_PROVIDER = {
    'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
}

AWS_ACCESS_KEY_ID = 'ASIA3KTXHTNGJU54NKA3'
AWS_SECRET_ACCESS_KEY = 'Sdn/qIm4H0avDZtMWNEAeyzJqDziFpKtLPOXNFgE'
AWS_SESSION_TOKEN = 'FQoGZXIvYXdzEFwaDNUi5zjvrLSbAq202yKCAp8J1BZXruRmiamkzuNuOUGAEHtOpAe35lLC1GvWxp1i2jZ07VcNZ8h6mghPtX5xaZKcyh2uTWd8cvVoSCi73ZXRpNvLb3OMj9zW4+w/J/8SPHENqqLDepzS4HMGhgWwZbRh9m5oWZUJnmFYYZn9EauzQXeZzZ8pumQCViZNyn0UByMXZC/U/7KvId+9Xia513Xvejro9A6MjH3TYrrxqmM03uQjRcMFhtsLZ8etW+sNNtbthxY2reIDJ2jpFmKvxG33hGs1z2zOQG3uJ7K9kGKW5xL/QMBBIsSBkE9Pp8TmdUj0xvZt6YOG3fuc/icfJKpU4v19HTrF+Aui1O6zU6GJKiirnv3qBQ=='

AWS_STORAGE_BUCKET_NAME = 'cdn.pointmall.hyosoooni'
AWS_S3_CUSTOM_DOMAIN = 'd3bie5xdra5ffr.cloudfront.net'
AWS_S3_URL = 'https://%s/' % AWS_S3_CUSTOM_DOMAIN
AWS_S3_SIGNATURE_VERSION = 's3v4'

STATIC_URL = '/static/'
STATIC_ROOT = 'static/'
STATICFILES_STORAGE = 'point_mall.storages.StaticStorage'

AWS_LOCATION = 'assets/'
ASSET_URL = '%s%s' % (AWS_S3_URL, AWS_LOCATION)
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
DEFAULT_FILE_STORAGE = 'point_mall.storages.FileStorage'